<?php
// $Id$

/**
 * @file
 * Add searching of The New York Public Library Digital Gallery from Drupal.
 */

/**
 * Implementation of hook_search().
 */
function nypl_digitalgallery_search($op = 'search', $keywords = null) {
  switch ($op) {
    case 'name':
      return t('Images');
    case 'reset':
      return;
    case 'search':
      // Fetch source info.
      $rows = variable_get('apachesolr_rows', 20);

      // Get pager info.
      global $pager_total, $pager_page_array, $pager_total_items, $locale;
      $page = isset($_GET['page']) ? $_GET['page'] : '';
      $pager_page_array = explode(',', $page);

      // Query sources.
      list($results, $total) = nypl_digitalgallery_query($keywords, max(0,
        $pager_page_array[0]) * $rows, $rows);

      /**
       * @see nypl_digitalgallery_query()
       */
      $pager_total_items[0] = $total + 1;
      $pager_total[0] = ceil($total / $rows);
      $pager_page_array[0] = max(0, min((int)$pager_page_array[0],
        ((int)$total) - 1));

      return $results;
  }
}

/**
 * Performs the query on digital gallery.
 *
 * @param $keywords 
 *   String of search terms
 *
 * @param $offset
 *   int containing starting point for result set
 *   
 * @param $limit
 *   int containing maximum size of result set
 *
 * @return array
 *   Contains an array of results and a string representing an approximate
 *   total of the number of results
 */
function nypl_digitalgallery_query($keywords, $offset, $limit) {
  
  $results = array();
  
  // Construct the query URL
  // per 6/11/09 discussion w. J. Dalton, hitting the rss2 feed means better
  // performance on DG's side right now as opposed to the atom feed; for some
  // reason, the atom feed does disk I/O rather than just hitting the index
  $query_url = 'http://digitalgallery.nypl.org/feeds/dev/rss2/?word='. 
    urlencode($keywords) .'&size=150&imgs='. $limit;  
  if ($offset > 0) { $query_url .= '&num='. $offset; }
  
  // Retrieve the query results
  $response = simplepie_get($query_url);
  
  // Since the response doesn't actually return the total number of results,
  // infer an approximate number from the atom:link[@rel='last'] value. If
  // $x = that value, then $x <= $total <= $x + $limit
  $chanlinks = $response->get_channel_tags(SIMPLEPIE_NAMESPACE_ATOM_10, "link");
  if (!empty($chanlinks)) {
    foreach ($chanlinks as $chanlink) {
      if ($chanlink['attribs'][NULL]['rel'] == 'last') {
        $last_link = $chanlink['attribs'][NULL]['href'];
      }
    }
  }
  if (preg_match("/num=(\d+)/", $last_link, $match)) { $last = $match[1]; }
  
  foreach ($response->get_items() as $item) {
    // Getting guid instead of link because it's shorter from the dg rss2 feed
    $links = $item->get_item_tags(SIMPLEPIE_NAMESPACE_RSS_20, "guid");
    $results[] = array(
      'link' => $links[0]['data'],
      'title' => $item->get_title(),
      'snippet' => $item->get_description(),
      'type' => 'Image (Digital Gallery)',
      'extra' => array(
        'thumbnail' => $item->get_enclosure()->get_thumbnail(),
      ),
    );
  }
  
  return array($results, $last);
}
